### ISSUE TITLE
Problems testing this example

### ISSUE THREAD

**Issue by jabrena** [cgfrost/cf-sample-app-nodejs#1]
I am trying to test this example using a CF Local instance:
https://docs.cloudfoundry.org/deploying/run-local.html
https://github.com/yudai/cf_nise_installer

and when I try to execute the command "cf push" I receive the following error:

```shell

Uploading cf-sample-app-nodejs...

Uploading 15.8K, 23 files
Done uploading
OK

Starting app cf-sample-app-nodejs in org DevBox / space dev as admin...
-----> Downloaded app package (8.0K)
    Cloning into '/tmp/buildpacks/nodejs-cf-buildpack'...
    Hello
/usr/bin/env: node: No such file or directory
/tmp/buildpacks/nodejs-cf-buildpack/bin/compile: line 9: node: command not found

/usr/bin/ruby
ruby 1.9.3p547 (2014-05-14 revision 45962) [x86_64-linux]
Goodbye
DEBUG> Not running in production, debug logging turned on. Using Node v0.10.26 a
t /tmp/buildpacks/nodejs-cf-buildpack/node_local/node_runtime/bin/node
DEBUG> 0 runtime  : /tmp/buildpacks/nodejs-cf-buildpack/node_local/node_runtime/
bin/node
DEBUG> 1 script   : /tmp/buildpacks/nodejs-cf-buildpack/bin/compile.js
DEBUG> 2 launcher : /tmp/buildpacks/nodejs-cf-buildpack/bin/compile
DEBUG> 3 BuildDir : /tmp/staged/app
DEBUG> 4 CacheDir : /tmp/cache
DEBUG> 5 EnvDir   : undefined
DEBUG> 6          : undefined
DEBUG>   execPath : /tmp/buildpacks/nodejs-cf-buildpack/node_local/node_runtime/
bin/node
DEBUG>   dirname  : /tmp/buildpacks/nodejs-cf-buildpack/lib
DEBUG>   filename : /tmp/buildpacks/nodejs-cf-buildpack/lib/Logger.js
DEBUG> Cache directory created.
       Added to cache "node-v0.10.26-linux-x64.tar.gz".
-----> No start /tmp/staged/app/.npmrc found, creating one to handle NPM self si
gned certificates bug.
-----> Setting Procfile to "web: npm start"
DEBUG> File copied to "/tmp/cache/node-v0.10.26-linux-x64.tar.gz" from "/tmp/bui
ldpacks/nodejs-cf-buildpack/node_local/node-v0.10.26-linux-x64.tar.gz".
-----> Requested version of Node 0.10.x resolved to version 0.10.40
-----> Unpacking "undefined" to "/tmp/staged/app/.buildpack/runtime".
fs.js:418
  binding.open(pathModule._makeLong(path),
          ^
TypeError: path must be a string
    at Object.fs.open (fs.js:418:11)
    at ReadStream.open (fs.js:1497:6)
    at new ReadStream (fs.js:1484:10)
    at Object.fs.createReadStream (fs.js:1438:10)
    at unpackNode (/tmp/buildpacks/nodejs-cf-buildpack/lib/Compiler.js:48:12)
    at getNode (/tmp/buildpacks/nodejs-cf-buildpack/lib/Compiler.js:90:13)
    at IncomingMessage.<anonymous> (/tmp/buildpacks/nodejs-cf-buildpack/lib/Comp
iler.js:107:21)
    at IncomingMessage.EventEmitter.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (_stream_readable.js:746:14)
    at IncomingMessage.EventEmitter.emit (events.js:92:17)
Staging failed: Buildpack compilation step failed

FAILED
BuildpackCompileFailed

```

What is the problem?

Many thanks in advance.

Juan Antonio

**Comment by jabrena** [comment]
I run my hello world example using the normal buildpack.
https://github.com/cloudfoundry/nodejs-buildpack

Detail:
https://github.com/jabrena/CloudFoundryLab/commit/504fa1972c06926e83443882ac60364637d715af

**Comment by cgfrost** [comment]
Hi,
This test app (https://github.com/cgfrost/cf-sample-app-nodejs) is only checked against the regular Pivotal CF Node Buildpack. I can't really comment about other buildpacks or apps. Using the `npm start` script to start the application is best practice and if you just want to deply from manifest you will need the `path` argument you added. 
Chris.

**Comment by jabrena** [comment]
Hi Chris, many thanks for the advice.

Juan Antonio
